language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install libsodium-dev
  
notifications:
  email:
    recipients:
      - benoit.thieurmel@datastorm.fr
